# Applications Config: imported from .env
spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driverClassName: ${SPRING_DATASOURCE_DRIVERCLASSNAME}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  h2:
    console:
      enabled: ${SPRING_H2_CONSOLE_ENABLED}
      path: ${SPRING_H2_CONSOLE_PATH}

jwt:
  secret: ${JWT_SECRET}